---
title: "NPOR: Comparison old and new measures"
author: Jelle van der Werff
date: 08/09/2023
output:
    html_notebook:
        code_folding: hide
        toc: true
        toc_float: true
---


# Preliminaries

```{r load-packages, echo = FALSE, warning = FALSE, message = FALSE}
############# PACKAGES AND OTHER PRELIMINARIES ############

# for easy loading of packages
if (!require("pacman")) install.packages("pacman")

# load packages
p_load(
  "stringr", "ini", "gdata", "plyr", "dplyr", "here", "ggplot2", "reshape2", "ggsci",
  "gghighlight", "ggridges", "viridis", "RColorBrewer", "lemon", "scico", "latex2exp", "GGally"
)

# for relative file paths (e.g. here('Input', 'file.csv'))
here::i_am(file.path("scripts", "interpreting_data", "comparison_old_new_measures_temponormalization.Rmd"))

source(here("scripts", "custom_ggplot_theme.R"))

# Knitr output settings
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%",
  fig.width = 10,
  fig.height = 10,
  cache = TRUE
)

# Load data
ITIs <- read.csv(here("data", "experiment", "processed", "ITIs.csv"))
ITIs.bytrial <- read.csv(here("data", "experiment", "processed", "ITIs_bytrial.csv"))
pp.measures <- read.csv(here("data", "experiment", "processed", "pp_measures.csv"))
```


```{r correlations}

labels <- as_labeller(c(
entropy_diff_avg = 'OLD:\nEntropy difference',
small_integers_vs_total_prop_avg = 'OLD:\nProportion of\nsmall integers',
edit_distance_avg = 'OLD:\nEdit distance',
tempo_deviation_avg = 'NEW:\nTempo deviation',
entropy_diff_norm_q_avg = 'NEW:\nEntropy difference',
asynchrony_norm_abs_avg =  'NEW:\nAsynchrony',
simple_ratio_introduced_avg = 'NEW:\nSimple ratio\nintroduced',
isochrony_introduced_avg = 'NEW:\nIsochrony introduced'
))


# Correlations between old and new measures
ggplot2::theme_set(theme_minimal())
ggpairs(pp.measures,
  columns = c("entropy_diff_avg", "small_integers_vs_total_prop_avg", "edit_distance_avg", "tempo_deviation_avg",
  "entropy_diff_norm_q_avg", "asynchrony_norm_abs_avg", "simple_ratio_introduced_avg"),
  title = "Correlations between participant measures", labeller = labels, aes(colour = condition, alpha = 0.8)
)

ggsave(here("plots", "correlations", "correlations_old_new.pdf"), width = 16, height = 9)

```