---
title: "NPOR: Plots"
author: Jelle van der Werff
date: 08/08/2023
output:
    html_notebook:
        code_folding: hide
        toc: true
        toc_float: true
---


# Preliminaries

```{r load-packages, echo = FALSE, warning = FALSE, message = FALSE}
############# PACKAGES AND OTHER PRELIMINARIES ############

# for easy loading of packages
if (!require("pacman")) install.packages("pacman")

# load packages
p_load(
  "stringr", "ini", "gdata", "plyr", "dplyr", "here", "ggplot2", "reshape2", "ggsci",
  "gghighlight", "ggridges", "viridis", "RColorBrewer", "lemon", "scico", "latex2exp", "GGally", "kableExtra",
  "cowplot"
)

# for relative file paths (e.g. here('Input', 'file.csv'))
here::i_am(file.path("scripts", "plots", "plots.Rmd"))

source(here("scripts", "custom_ggplot_theme.R"))

# Knitr output settings
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%",
  fig.width = 10,
  fig.height = 10,
  cache = TRUE
)

labels <- as_labeller(c(
  "400" = "400 ms",
  "600" = "600 ms",
  "4" = "4 events",
  "5" = "5 events"
))
```


```{r load-data}
ITIs <- read.csv(here("data", "experiment", "processed", "ITIs.csv"))
ITIs.bytrial <- read.csv(here("data", "experiment", "processed", "ITIs_bytrial.csv"))
pp.measures <- read.csv(here("data", "experiment", "processed", "pp_measures.csv"))
interval.ratios <- read.csv(here("data", "experiment", "processed", "ratios_introduced.csv"))
```

```{r datatypes}
pp.measures$pp_id_behav <- as.factor(pp.measures$pp_id_behav)
pp.measures$stim_tempo_intended <- as.factor(pp.measures$stim_tempo_intended)
pp.measures$length <- as.factor(pp.measures$length)

pp.measures$condition <- as.factor(paste(pp.measures$stim_tempo_intended, pp.measures$length, sep = "_"))


ITIs$pp_id_behav <- as.factor(ITIs$pp_id_behav)
ITIs$condition <- as.factor(paste(ITIs$stim_tempo_intended, ITIs$length, sep = "_"))

ITIs.bytrial$condition <- as.factor(paste(ITIs.bytrial$stim_tempo_intended, ITIs.bytrial$length, sep = "_"))
ITIs.bytrial$pp_id_behav <- as.factor(ITIs.bytrial$pp_id_behav)
```


# Descriptives table


```{r table}
descriptives.table <- ddply(ITIs, .(stim_tempo_intended, length), summarize,
  n_taps = length(resp_iti),
  n_trials = length(unique(sequence_id)),
  mean_ioi = mean(stim_ioi),
  median_ioi = median(stim_ioi),
  sd_ioi = sd(stim_ioi),
  mean_iti = mean(resp_iti),
  median_iti = median(resp_iti),
  sd_iti = sd(resp_iti),
)

descriptives.table2 <- ddply(ITIs, .(stim_tempo_intended, length), summarize,
  G_resp = mean(G_resp),
  entropy_diff_norm_q_avg = mean(entropy_diff_norm_q),
  asynchrony_norm_abs_avg = mean(asynchrony_norm_abs),
  simple_ratio_introduced_avg = mean(simple_ratio_introduced))


# kable
kable(descriptives.table) %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
kable(descriptives.table2) %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

# Measures for final analysis

## Tempo deviation

```{r tempo-diff}
ggplot(pp.measures, aes(x = condition, y = tempo_deviation_abs_avg, fill = condition, colour = condition)) +
  geom_violin(alpha = 0.7, show.legend = FALSE) +
  geom_point(size = 1, show.legend = FALSE, colour = "black", alpha = 0.3) +
  scale_x_discrete(labels = c(
    "400_4" = "400 ms\n4 events",
    "400_5" = "400 ms\n5 events",
    "600_4" = "600 ms\n4 events",
    "600_5" = "600 ms\n5 events"
  )) +
  stat_summary(geom = "pointrange", size = 1, linewidth = 1.5, colour = "black", show.legend = FALSE) +
  theme_jelle() +
  labs(
    x = "Condition",
    y = "Tempo deviation",
    title = "Absolute tempo deviation",
    subtitle = "Calculated as the absolute ratio between the response and stimulus tempo"
  ) +
  theme(plot.caption = element_text(hjust = 0))

ggsave(here("plots", "tempo_deviation.pdf"))
```

## G measure

```{r g-score}
ggplot(pp.measures, aes(x = condition, y = G_resp, fill = condition, colour = condition)) +
  geom_violin(alpha = 0.7, show.legend = FALSE) +
  geom_point(size = 1, show.legend = FALSE, colour = "black", alpha = 0.3) +
  scale_x_discrete(labels = c(
    "400_4" = "400 ms\n4 events",
    "400_5" = "400 ms\n5 events",
    "600_4" = "600 ms\n4 events",
    "600_5" = "600 ms\n5 events"
  )) +
  stat_summary(geom = "pointrange", size = 1, linewidth = 1.5, colour = "black", show.legend = FALSE) +
  theme_jelle() +
  labs(
    x = "Condition",
    y = expression(italic(G) ~ measure),
    title = "Grammatical redundancy by condition",
    subtitle = "Higher values mean more grammatical redundancy",
    caption = "Interpretation: Let's say a participant always taps a quarternote and then an eighth note.
This means the quarternote-eighth note combination is redundant, as it could have been
one symbol, so G is higher. The more different combinations of symbols a participant uses,
the lower the G score."
  ) +
  theme(plot.caption = element_text(hjust = 0))



ggsave(here("plots", "g-score.pdf"))
ggsave(here("plots", "g-score.png"), dpi = 300)
```


## Entropy

```{r entropy}
ggplot(pp.measures, aes(x = condition, y = entropy_diff_norm_q_avg, fill = condition, colour = condition)) +
  geom_violin(alpha = 0.7, show.legend = FALSE) +
  geom_point(size = 1, show.legend = FALSE, colour = "black", alpha = 0.3) +
  scale_x_discrete(labels = c(
    "400_4" = "400 ms\n4 events",
    "400_5" = "400 ms\n5 events",
    "600_4" = "600 ms\n4 events",
    "600_5" = "600 ms\n5 events"
  )) +
  stat_summary(geom = "pointrange", size = 1, linewidth = 1.5, colour = "black", show.legend = FALSE) +
  theme_jelle() +
  labs(
    y = "Entropy difference", title = "Entropy difference by participant and condition",
    subtitle = "Negative values mean participants decreased entropy", colour = "Participant"
  )
ggsave(here("plots", "entropy.pdf"))
ggsave(here("plots", "entropy.png"), dpi = 300)
```

## Number of small integer ratios introduced

```{r simple-integers}
ggplot(pp.measures, aes(
  x = condition,
  y = simple_ratio_introduced_avg,
  colour = condition, fill = condition
 )) +
   stat_summary(geom = "pointrange", size = 1, linewidth = 1.5, colour = "black", show.legend = FALSE) +
  geom_violin(alpha = 0.7, show.legend = FALSE) +
  geom_point(size = 1, show.legend = FALSE, colour = "black", alpha = 0.3) +
  scale_x_discrete(labels = c(
    "400_4" = "400 ms\n4 events",
    "400_5" = "400 ms\n5 events",
    "600_4" = "600 ms\n4 events",
    "600_5" = "600 ms\n5 events"
  )) +
theme(
  axis.title.x = element_blank(),
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank()
) +
  labs(
    x = "Condition", y = "Number of small integer ratios introduced",
    title = "Mean number of small integer ratios introduced in trial",
    subtitle = "Negative values mean a reduction of small integer ratios from stimulus to response",
    caption = "Simple integer ratios were isochronous, binary, and ternary interval ratios"
  ) +
  theme_jelle()

ggsave(here("plots", "small_integers.pdf"))
ggsave(here("plots", "small_integers.png"), dpi = 300)
```


## Asynchrony
```{r asynchrony}

ggplot(ITIs.bytrial, aes(y = asynchrony_norm_abs_trialsum, x = 1, colour = pp_id_behav)) +
  stat_summary(geom = "pointrange", position = position_dodge(width = 0.1), show.legend = FALSE) +
  facet_grid(rows = vars(length), cols = vars(stim_tempo_intended), labeller = labels) +
  theme_jelle() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  labs(
    y = "Sum of absolute asynchronies in trial (normalized)", title = "Asynchrony within trial by participant and condition",
    subtitle = "Sequences were normalized such that 1 represents the total duration of the sequence")

ggsave(here("plots", "asynchrony.pdf"))
ggsave(here("plots", "asynchrony.png"), dpi=300)

```


# Correlations


## All

```{r correlations}
labels <- as_labeller(c(
  "G_resp" = "G (response)",
  "entropy_diff_norm_q_avg" = "Entropy difference",
  "asynchrony_norm_abs_avg" = "Asynchrony",
  "iti_cov_norm" = "ITI CoV",
  "simple_ratio_introduced_avg" = "Introduced simple integer ratios",
  "tempo_deviation_abs_avg" = "Tempo deviation"
))

levels(pp.measures$condition) <- c("400 ms (4)", "400 ms (5)", "600 ms (4)", "600 ms (5)")

# Scatterplots with combinations between all measures
ggplot2::theme_set(theme_minimal())
ggpairs(pp.measures,
  columns = c("G_resp", "entropy_diff_norm_q_avg", "iti_cov_norm",
  "asynchrony_norm_abs_avg", "simple_ratio_introduced_avg", "tempo_deviation_abs_avg"),
  title = "Correlations between participant measures", labeller = labels, aes(colour = condition, alpha = 0.8)
)

ggsave(here("plots", "correlations", "correlations.pdf"))
ggsave(here("plots", "correlations", "correlations.png"))
```

## Variability (ITI CoV)

```{r cov}



```


# Other plots

## ITI ridges

```{r ITI-ridges, fig.width = 20, fig.height = 20}
ggplot(ITIs, aes(x = resp_iti, y = pp_id, fill = pp_id, colour = pp_id)) +
  geom_density_ridges(scale = 4, alpha = 0.9, show.legend = FALSE, color = "white") +
  facet_rep_grid(rows = vars(length), cols = vars(stim_tempo_intended), labeller = labels, repeat.tick.labels = "x") +
  theme_jelle() +
  scale_x_continuous(breaks = seq(0, 1200, 200)) +
  coord_cartesian(xlim = c(0, 1200)) +
  labs(
    x = "ITI [ms]", y = "Participant", title = "Inter-tap intervals produced by participants by condition",
    subtitle = "Dashed line indicates (intended) tempo of condition"
  ) +
  geom_vline(data = ITIs[ITIs$stim_tempo_intended == 400, ], aes(xintercept = 400), linetype = "dashed", color = "grey") +
  geom_vline(data = ITIs[ITIs$stim_tempo_intended == 600, ], aes(xintercept = 600), linetype = "dashed", color = "grey")
ggsave(here("plots", "ITI-ridges.pdf"), width = 20, height = 20)
```

```{r binned entropy diff}

ITIs$entropy_diff_norm_q <- round(ITIs$entropy_diff_norm_q, 1)

ITIs$binned_entropy <- cut(ITIs$entropy_diff_norm_q, breaks = c(-2, -1, 0, 1, 2), include.lowest = TRUE, right = FALSE)


ggplot(ITIs, aes(x = binned_entropy, y = asynchrony_norm_abs)) +
stat_summary(geom = "pointrange", show.legend = FALSE) +
facet_rep_wrap(~length + stim_tempo_intended, labeller = labels, repeat.tick.labels = TRUE) +
theme(
  axis.ticks.x = element_blank()
) +
theme(axis.text.x = element_text(size = 8)) +
labs(x = "Entropy difference", y = "Asynchrony", title = "Asynchrony by entropy difference") +
theme_jelle()

ggsave(here("plots", "binned-entropy.pdf"))

```