---
title: "NPOR: Analysis of group variability"
author: jellevanderwerff
date: 04/04/2022
output:
    html_notebook:
        code_folding: hide
---


```{r}
# for easy loading of packages
if (!require("pacman")) install.packages("pacman")

# load packages
p_load("ggplot2", "dplyr", "knitr", "kableExtra")

# for relative file paths (e.g. here('Input', 'file.csv'))
here::i_am(file.path("stats", "condition_variability_behavioural_measures.Rmd"))

# select correct here
here <- here::here

# Load custom helper functions
source(here("scripts", "helper_functions.R"))

# Load custom theme
source(here("scripts", "jelle_ggplot_theme.R"))

# Load dataframe
df <- read.csv(here("data", "experiment", "processed", "pp_measures.csv"))
```

```{r stats}

measures.variability.by.condition <- ddply(df, .(condition), summarise,
                                           entropy_sd = sd(entropy_diff_norm_q_avg),
                                           cov_sd = sd(iti_ioi_cov_diff_avg),
                                           isochrony_introduced_sd = sd(isochrony_introduced),
                                           binary_or_ternary_introduced_sd = sd(binary_or_ternary_introduced))
kable(measures.variability.by.condition) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center")

```


```{r entropy-boxplot}

# plot the variances of the different conditions
ggplot(df, aes(x = condition, y = entropy_diff_norm_q_avg)) +
geom_boxplot() +
theme_jelle()

# plot the variances for isochrony introduced
ggplot(df, aes(x = condition, y = isochrony_introduced)) +
geom_boxplot() +
theme_jelle()

# plot the variances for binary or ternary introduced
ggplot(df, aes(x = condition, y = binary_or_ternary_introduced)) +
geom_boxplot() +
theme_jelle()

```

```{r bartlett}

# do bartlett's test for comparing the variance in the different conditions
entropy <- bartlett.test(df$entropy_diff_norm_q_avg, df$condition)

asynchrony <- bartlett.test(df$asynchrony_norm_abs_avg, df$condition)
variability <- bartlett.test(df$variability_norm_q_avg, df$condition)

```


```{r levene}

# do levene's test for comparing the variance in the different conditions
G_levene <- leveneTest(G_resp ~ condition, data = df)

isoc_levene <- leveneTest(isochrony_introduced ~ condition, data = df)
binaryternary_levene <- leveneTest(binary_or_ternary_introduced ~ condition, data = df)

```